apiVersion: apps/v1
kind:   Deployment
metadata:
    name:   client-Deployment
spec:
    replicas:   1
    selector:
        matchLabels:
            component:  web
    template:
        metadata:
            labels:
                component:
        spec:
            containers:
                -   name:   client
                    image:  barrybt23/multi-client
                    ports:
                        -   containerPort:  3000